name: CI with Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cache dependencies
      - name: Cache npm dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-d79da0f
          restore-keys: |
            cache-

      # Step 3: Prime the cache
      - name: prime-cache-d79da0f
        run: |
          echo "Cache hit result: ${{ steps.cache-step.outputs.cache-hit }}"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Run your tests
      - name: Run tests
        run: npm test
